/* Automatically generated by './build/bin/build-el.js' */
import Icon from 'element-ui/packages/icon/index.js';
// Icon.name = "FIcon"
/* istanbul ignore next */
Icon.install = function(Vue) {
    Vue.component("FIcon", Icon);
};
export default Icon;
