/* Automatically generated by './build/bin/build-el.js' */
import Submenu from 'element-ui/packages/submenu/index.js';
// Submenu.name = "FSubmenu"
/* istanbul ignore next */
Submenu.install = function(Vue) {
    Vue.component("FSubmenu", Submenu);
};
export default Submenu;
