/* Automatically generated by './build/bin/build-el.js' */
import Dropdown from 'element-ui/packages/dropdown/index.js';
// Dropdown.name = "FDropdown"
/* istanbul ignore next */
Dropdown.install = function(Vue) {
    Vue.component("FDropdown", Dropdown);
};
export default Dropdown;
