/* Automatically generated by './build/bin/build-el.js' */
import DropdownItem from 'element-ui/packages/dropdown-item/index.js';
// DropdownItem.name = "FDropdownItem"
/* istanbul ignore next */
DropdownItem.install = function(Vue) {
    Vue.component("FDropdownItem", DropdownItem);
};
export default DropdownItem;
