/* Automatically generated by './build/bin/build-el.js' */
import TimeSelect from 'element-ui/packages/time-select/index.js';
// TimeSelect.name = "FTimeSelect"
/* istanbul ignore next */
TimeSelect.install = function(Vue) {
    Vue.component("FTimeSelect", TimeSelect);
};
export default TimeSelect;
