/* Automatically generated by './build/bin/build-el.js' */
import FormItem from 'element-ui/packages/form-item/index.js';
// FormItem.name = "FFormItem"
/* istanbul ignore next */
FormItem.install = function(Vue) {
    Vue.component("FFormItem", FormItem);
};
export default FormItem;
