/* Automatically generated by './build/bin/build-el.js' */
import Empty from 'element-ui/packages/empty/index.js';
// Empty.name = "FEmpty"
/* istanbul ignore next */
Empty.install = function(Vue) {
    Vue.component("FEmpty", Empty);
};
export default Empty;
