/* Automatically generated by './build/bin/build-el.js' */
import Skeleton from 'element-ui/packages/skeleton/index.js';
// Skeleton.name = "FSkeleton"
/* istanbul ignore next */
Skeleton.install = function(Vue) {
    Vue.component("FSkeleton", Skeleton);
};
export default Skeleton;
