/* Automatically generated by './build/bin/build-el.js' */
import TimelineItem from 'element-ui/packages/timeline-item/index.js';
// TimelineItem.name = "FTimelineItem"
/* istanbul ignore next */
TimelineItem.install = function(Vue) {
    Vue.component("FTimelineItem", TimelineItem);
};
export default TimelineItem;
