/* Automatically generated by './build/bin/build-el.js' */
import Breadcrumb from 'element-ui/packages/breadcrumb/index.js';
// Breadcrumb.name = "FBreadcrumb"
/* istanbul ignore next */
Breadcrumb.install = function(Vue) {
    Vue.component("FBreadcrumb", Breadcrumb);
};
export default Breadcrumb;
