/* Automatically generated by './build/bin/build-el.js' */
import Form from 'element-ui/packages/form/index.js';
// Form.name = "FForm"
/* istanbul ignore next */
Form.install = function(Vue) {
    Vue.component("FForm", Form);
};
export default Form;
