/* Automatically generated by './build/bin/build-el.js' */
import Transfer from 'element-ui/packages/transfer/index.js';
// Transfer.name = "FTransfer"
/* istanbul ignore next */
Transfer.install = function(Vue) {
    Vue.component("FTransfer", Transfer);
};
export default Transfer;
