/* Automatically generated by './build/bin/build-el.js' */
import Upload from 'element-ui/packages/upload/index.js';
// Upload.name = "FUpload"
/* istanbul ignore next */
Upload.install = function(Vue) {
    Vue.component("FUpload", Upload);
};
export default Upload;
