/* Automatically generated by './build/bin/build-el.js' */
import Backtop from 'element-ui/packages/backtop/index.js';
// Backtop.name = "FBacktop"
/* istanbul ignore next */
Backtop.install = function(Vue) {
    Vue.component("FBacktop", Backtop);
};
export default Backtop;
