/* Automatically generated by './build/bin/build-el.js' */
import TabPane from 'element-ui/packages/tab-pane/index.js';
// TabPane.name = "FTabPane"
/* istanbul ignore next */
TabPane.install = function(Vue) {
    Vue.component("FTabPane", TabPane);
};
export default TabPane;
