/* Automatically generated by './build/bin/build-el.js' */
import CheckboxGroup from 'element-ui/packages/checkbox-group/index.js';
// CheckboxGroup.name = "FCheckboxGroup"
/* istanbul ignore next */
CheckboxGroup.install = function(Vue) {
    Vue.component("FCheckboxGroup", CheckboxGroup);
};
export default CheckboxGroup;
