/* Automatically generated by './build/bin/build-el.js' */
import PageHeader from 'element-ui/packages/page-header/index.js';
// PageHeader.name = "FPageHeader"
/* istanbul ignore next */
PageHeader.install = function(Vue) {
    Vue.component("FPageHeader", PageHeader);
};
export default PageHeader;
