/* Automatically generated by './build/bin/build-el.js' */
import Scrollbar from 'element-ui/packages/scrollbar/index.js';
// Scrollbar.name = "FScrollbar"
/* istanbul ignore next */
Scrollbar.install = function(Vue) {
    Vue.component("FScrollbar", Scrollbar);
};
export default Scrollbar;
