/* Automatically generated by './build/bin/build-el.js' */
import Image from 'element-ui/packages/image/index.js';
// Image.name = "FImage"
/* istanbul ignore next */
Image.install = function(Vue) {
    Vue.component("FImage", Image);
};
export default Image;
