/* Automatically generated by './build/bin/build-el.js' */
import Steps from 'element-ui/packages/steps/index.js';
// Steps.name = "FSteps"
/* istanbul ignore next */
Steps.install = function(Vue) {
    Vue.component("FSteps", Steps);
};
export default Steps;
