/* Automatically generated by './build/bin/build-el.js' */
import Step from 'element-ui/packages/step/index.js';
// Step.name = "FStep"
/* istanbul ignore next */
Step.install = function(Vue) {
    Vue.component("FStep", Step);
};
export default Step;
