/* Automatically generated by './build/bin/build-el.js' */
import Pagination from 'element-ui/packages/pagination/index.js';
// Pagination.name = "FPagination"
/* istanbul ignore next */
Pagination.install = function(Vue) {
    Vue.component("FPagination", Pagination);
};
export default Pagination;
