/* Automatically generated by './build/bin/build-el.js' */
import Switch from 'element-ui/packages/switch/index.js';
// Switch.name = "FSwitch"
/* istanbul ignore next */
Switch.install = function(Vue) {
    Vue.component("FSwitch", Switch);
};
export default Switch;
