/* Automatically generated by './build/bin/build-el.js' */
import Cascader from 'element-ui/packages/cascader/index.js';
// Cascader.name = "CCascader"
/* istanbul ignore next */
Cascader.install = function(Vue) {
    Vue.component("FCascader", Cascader);
};
export default Cascader;
