/* Automatically generated by './build/bin/build-el.js' */
import RadioGroup from 'element-ui/packages/radio-group/index.js';
// RadioGroup.name = "FRadioGroup"
/* istanbul ignore next */
RadioGroup.install = function(Vue) {
    Vue.component("FRadioGroup", RadioGroup);
};
export default RadioGroup;
