/* Automatically generated by './build/bin/build-el.js' */
import Select from 'element-ui/packages/select/index.js';
// Select.name = "FSelect"
/* istanbul ignore next */
Select.install = function(Vue) {
    Vue.component("FSelect", Select);
};
export default Select;
