/* Automatically generated by './build/bin/build-el.js' */
import CheckboxButton from 'element-ui/packages/checkbox-button/index.js';
// CheckboxButton.name = "FCheckboxButton"
/* istanbul ignore next */
CheckboxButton.install = function(Vue) {
    Vue.component("FCheckboxButton", CheckboxButton);
};
export default CheckboxButton;
