/* Automatically generated by './build/bin/build-el.js' */
import Header from 'element-ui/packages/header/index.js';
// Header.name = "FHeader"
/* istanbul ignore next */
Header.install = function(Vue) {
    Vue.component("FHeader", Header);
};
export default Header;
