/* Automatically generated by './build/bin/build-el.js' */
import CascaderPanel from 'element-ui/packages/cascader-panel/index.js';
// CascaderPanel.name = "FCascaderPanel"
/* istanbul ignore next */
CascaderPanel.install = function(Vue) {
    Vue.component("FCascaderPanel", CascaderPanel);
};
export default CascaderPanel;
