/* Automatically generated by './build/bin/build-el.js' */
import Popconfirm from 'element-ui/packages/popconfirm/index.js';
// Popconfirm.name = "FPopconfirm"
/* istanbul ignore next */
Popconfirm.install = function(Vue) {
    Vue.component("FPopconfirm", Popconfirm);
};
export default Popconfirm;
