/* Automatically generated by './build/bin/build-el.js' */
import Drawer from 'element-ui/packages/drawer/index.js';
// Drawer.name = "FDrawer"
/* istanbul ignore next */
Drawer.install = function(Vue) {
    Vue.component("FDrawer", Drawer);
};
export default Drawer;
