/* Automatically generated by './build/bin/build-el.js' */
import Slider from 'element-ui/packages/slider/index.js';
// Slider.name = "FSlider"
/* istanbul ignore next */
Slider.install = function(Vue) {
    Vue.component("FSlider", Slider);
};
export default Slider;
