/* Automatically generated by './build/bin/build-el.js' */
import Card from 'element-ui/packages/card/index.js';
// Card.name = "CCard"
/* istanbul ignore next */
Card.install = function(Vue) {
    Vue.component("FCard", Card);
};
export default Card;
