/* Automatically generated by './build/bin/build-el.js' */
import Collapse from 'element-ui/packages/collapse/index.js';
// Collapse.name = "FCollapse"
/* istanbul ignore next */
Collapse.install = function(Vue) {
    Vue.component("FCollapse", Collapse);
};
export default Collapse;
