/* Automatically generated by './build/bin/build-el.js' */
import Alert from 'element-ui/packages/alert/index.js';
// Alert.name = "FAlert"
/* istanbul ignore next */
Alert.install = function(Vue) {
    Vue.component("FAlert", Alert);
};
export default Alert;
