/* Automatically generated by './build/bin/build-el.js' */
import Checkbox from 'element-ui/packages/checkbox/index.js';
// Checkbox.name = "FCheckbox"
/* istanbul ignore next */
Checkbox.install = function(Vue) {
    Vue.component("FCheckbox", Checkbox);
};
export default Checkbox;
