/* Automatically generated by './build/bin/build-el.js' */
import Avatar from 'element-ui/packages/avatar/index.js';
// Avatar.name = "FAvatar"
/* istanbul ignore next */
Avatar.install = function(Vue) {
    Vue.component("FAvatar", Avatar);
};
export default Avatar;
