/* Automatically generated by './build/bin/build-el.js' */
import SkeletonItem from 'element-ui/packages/skeleton-item/index.js';
// SkeletonItem.name = "FSkeletonItem"
/* istanbul ignore next */
SkeletonItem.install = function(Vue) {
    Vue.component("FSkeletonItem", SkeletonItem);
};
export default SkeletonItem;
