/* Automatically generated by './build/bin/build-el.js' */
import ColorPicker from 'element-ui/packages/color-picker/index.js';
// ColorPicker.name = "FColorPicker"
/* istanbul ignore next */
ColorPicker.install = function(Vue) {
    Vue.component("FColorPicker", ColorPicker);
};
export default ColorPicker;
