/* Automatically generated by './build/bin/build-el.js' */
import Divider from 'element-ui/packages/divider/index.js';
// Divider.name = "FDivider"
/* istanbul ignore next */
Divider.install = function(Vue) {
    Vue.component("FDivider", Divider);
};
export default Divider;
