/* Automatically generated by './build/bin/build-el.js' */
import Main from 'element-ui/packages/main/index.js';
// Main.name = "FMain"
/* istanbul ignore next */
Main.install = function(Vue) {
    Vue.component("FMain", Main);
};
export default Main;
