/* Automatically generated by './build/bin/build-el.js' */
import CollapseItem from 'element-ui/packages/collapse-item/index.js';
// CollapseItem.name = "FCollapseItem"
/* istanbul ignore next */
CollapseItem.install = function(Vue) {
    Vue.component("FCollapseItem", CollapseItem);
};
export default CollapseItem;
