/* Automatically generated by './build/bin/build-el.js' */
import Footer from 'element-ui/packages/footer/index.js';
// Footer.name = "FFooter"
/* istanbul ignore next */
Footer.install = function(Vue) {
    Vue.component("FFooter", Footer);
};
export default Footer;
