/* Automatically generated by './build/bin/build-el.js' */
import Input from 'element-ui/packages/input/index.js';
// Input.name = "FInput"
/* istanbul ignore next */
Input.install = function(Vue) {
    Vue.component("FInput", Input);
};
export default Input;
