/* Automatically generated by './build/bin/build-el.js' */
import Aside from 'element-ui/packages/aside/index.js';
// Aside.name = "FAside"
/* istanbul ignore next */
Aside.install = function(Vue) {
    Vue.component("FAside", Aside);
};
export default Aside;
