/* Automatically generated by './build/bin/build-el.js' */
import Col from 'element-ui/packages/col/index.js';
// Col.name = "FCol"
/* istanbul ignore next */
Col.install = function(Vue) {
    Vue.component("FCol", Col);
};
export default Col;
