/* Automatically generated by './build/bin/build-el.js' */
import Tabs from 'element-ui/packages/tabs/index.js';
// Tabs.name = "FTabs"
/* istanbul ignore next */
Tabs.install = function(Vue) {
    Vue.component("FTabs", Tabs);
};
export default Tabs;
