/* Automatically generated by './build/bin/build-el.js' */
import Link from 'element-ui/packages/link/index.js';
// Link.name = "FLink"
/* istanbul ignore next */
Link.install = function(Vue) {
    Vue.component("FLink", Link);
};
export default Link;
