/* Automatically generated by './build/bin/build-el.js' */
import InputNumber from 'element-ui/packages/input-number/index.js';
// InputNumber.name = "FInputNumber"
/* istanbul ignore next */
InputNumber.install = function(Vue) {
    Vue.component("FInputNumber", InputNumber);
};
export default InputNumber;
