/* Automatically generated by './build/bin/build-el.js' */
import MenuItem from 'element-ui/packages/menu-item/index.js';
// MenuItem.name = "FMenuItem"
/* istanbul ignore next */
MenuItem.install = function(Vue) {
    Vue.component("FMenuItem", MenuItem);
};
export default MenuItem;
