/* Automatically generated by './build/bin/build-el.js' */
import Popover from 'element-ui/packages/popover/index.js';
// Popover.name = "FPopover"
/* istanbul ignore next */
Popover.install = function(Vue) {
    Vue.component("FPopover", Popover);
};
export default Popover;
