/* Automatically generated by './build/bin/build-el.js' */
import Tree from 'element-ui/packages/tree/index.js';
// Tree.name = "FTree"
/* istanbul ignore next */
Tree.install = function(Vue) {
    Vue.component("FTree", Tree);
};
export default Tree;
