/* Automatically generated by './build/bin/build-el.js' */
import ButtonGroup from 'element-ui/packages/button-group/index.js';
// ButtonGroup.name = "FButtonGroup"
/* istanbul ignore next */
ButtonGroup.install = function(Vue) {
    Vue.component("FButtonGroup", ButtonGroup);
};
export default ButtonGroup;
