/* Automatically generated by './build/bin/build-el.js' */
import OptionGroup from 'element-ui/packages/option-group/index.js';
// OptionGroup.name = "FOptionGroup"
/* istanbul ignore next */
OptionGroup.install = function(Vue) {
    Vue.component("FOptionGroup", OptionGroup);
};
export default OptionGroup;
