/* Automatically generated by './build/bin/build-el.js' */
import Container from 'element-ui/packages/container/index.js';
// Container.name = "FContainer"
/* istanbul ignore next */
Container.install = function(Vue) {
    Vue.component("FContainer", Container);
};
export default Container;
