/* Automatically generated by './build/bin/build-el.js' */
import Row from 'element-ui/packages/row/index.js';
// Row.name = "FRow"
/* istanbul ignore next */
Row.install = function(Vue) {
    Vue.component("FRow", Row);
};
export default Row;
