/* Automatically generated by './build/bin/build-el.js' */
import Table from 'element-ui/packages/table/index.js';
// Table.name = "FTable"
/* istanbul ignore next */
Table.install = function(Vue) {
    Vue.component("FTable", Table);
};
export default Table;
