/* Automatically generated by './build/bin/build-el.js' */
import Badge from 'element-ui/packages/badge/index.js';
// Badge.name = "FBadge"
/* istanbul ignore next */
Badge.install = function(Vue) {
    Vue.component("FBadge", Badge);
};
export default Badge;
