/* Automatically generated by './build/bin/build-el.js' */
import BreadcrumbItem from 'element-ui/packages/breadcrumb-item/index.js';
// BreadcrumbItem.name = "FBreadcrumbItem"
/* istanbul ignore next */
BreadcrumbItem.install = function(Vue) {
    Vue.component("FBreadcrumbItem", BreadcrumbItem);
};
export default BreadcrumbItem;
