/* Automatically generated by './build/bin/build-el.js' */
import Option from 'element-ui/packages/option/index.js';
// Option.name = "FOption"
/* istanbul ignore next */
Option.install = function(Vue) {
    Vue.component("FOption", Option);
};
export default Option;
