/* Automatically generated by './build/bin/build-el.js' */
import Timeline from 'element-ui/packages/timeline/index.js';
// Timeline.name = "FTimeline"
/* istanbul ignore next */
Timeline.install = function(Vue) {
    Vue.component("FTimeline", Timeline);
};
export default Timeline;
