/* Automatically generated by './build/bin/build-el.js' */
import Autocomplete from 'element-ui/packages/autocomplete/index.js';
// Autocomplete.name = "FAutocomplete"
/* istanbul ignore next */
Autocomplete.install = function(Vue) {
    Vue.component("FAutocomplete", Autocomplete);
};
export default Autocomplete;
