/* Automatically generated by './build/bin/build-el.js' */
import Rate from 'element-ui/packages/rate/index.js';
// Rate.name = "FRate"
/* istanbul ignore next */
Rate.install = function(Vue) {
    Vue.component("FRate", Rate);
};
export default Rate;
