/* Automatically generated by './build/bin/build-el.js' */
import Progress from 'element-ui/packages/progress/index.js';
// Progress.name = "FProgress"
/* istanbul ignore next */
Progress.install = function(Vue) {
    Vue.component("FProgress", Progress);
};
export default Progress;
