/* Automatically generated by './build/bin/build-el.js' */
import Menu from 'element-ui/packages/menu/index.js';
// Menu.name = "FMenu"
/* istanbul ignore next */
Menu.install = function(Vue) {
    Vue.component("FMenu", Menu);
};
export default Menu;
