/* Automatically generated by './build/bin/build-el.js' */
import Tooltip from 'element-ui/packages/tooltip/index.js';
// Tooltip.name = "FTooltip"
/* istanbul ignore next */
Tooltip.install = function(Vue) {
    Vue.component("FTooltip", Tooltip);
};
export default Tooltip;
