/* Automatically generated by './build/bin/build-el.js' */
import DropdownMenu from 'element-ui/packages/dropdown-menu/index.js';
// DropdownMenu.name = "FDropdownMenu"
/* istanbul ignore next */
DropdownMenu.install = function(Vue) {
    Vue.component("FDropdownMenu", DropdownMenu);
};
export default DropdownMenu;
