/* Automatically generated by './build/bin/build-el.js' */
import Carousel from 'element-ui/packages/carousel/index.js';
// Carousel.name = "FCarousel"
/* istanbul ignore next */
Carousel.install = function(Vue) {
    Vue.component("FCarousel", Carousel);
};
export default Carousel;
