/* Automatically generated by './build/bin/build-el.js' */
import RadioButton from 'element-ui/packages/radio-button/index.js';
// RadioButton.name = "FRadioButton"
/* istanbul ignore next */
RadioButton.install = function(Vue) {
    Vue.component("FRadioButton", RadioButton);
};
export default RadioButton;
