/* Automatically generated by './build/bin/build-el.js' */
import Dialog from './src/index.vue';

// Dialog.name = "FDialog"
/* istanbul ignore next */
Dialog.install = function(Vue) {
    Vue.component("FDialog", Dialog);
};
export default Dialog;
