/* Automatically generated by './build/bin/build-el.js' */
import Radio from 'element-ui/packages/radio/index.js';
// Radio.name = "FRadio"
/* istanbul ignore next */
Radio.install = function(Vue) {
    Vue.component("FRadio", Radio);
};
export default Radio;
