/* Automatically generated by './build/bin/build-el.js' */
import CarouselItem from 'element-ui/packages/carousel-item/index.js';
// CarouselItem.name = "CCarouselItem"
/* istanbul ignore next */
CarouselItem.install = function(Vue) {
    Vue.component("FCarouselItem", CarouselItem);
};
export default CarouselItem;
