/* Automatically generated by './build/bin/build-el.js' */
import Spinner from 'element-ui/packages/spinner/index.js';
// Spinner.name = "FSpinner"
/* istanbul ignore next */
Spinner.install = function(Vue) {
    Vue.component("FSpinner", Spinner);
};
export default Spinner;
