/* Automatically generated by './build/bin/build-el.js' */
import InfiniteScroll from 'element-ui/packages/infinite-scroll';

/* istanbul ignore next */
InfiniteScroll.install = function(Vue) {
    Vue.directive(InfiniteScroll.name, InfiniteScroll);
};
export default InfiniteScroll;
