/* Automatically generated by './build/bin/build-el.js' */
import TimePicker from 'element-ui/packages/time-picker/index.js';
// TimePicker.name = "FTimePicker"
/* istanbul ignore next */
TimePicker.install = function(Vue) {
    Vue.component("FTimePicker", TimePicker);
};
export default TimePicker;
