/* Automatically generated by './build/bin/build-el.js' */
import TableColumn from 'element-ui/packages/table-column/index.js';
// TableColumn.name = "FTableColumn"
/* istanbul ignore next */
TableColumn.install = function(Vue) {
    Vue.component("FTableColumn", TableColumn);
};
export default TableColumn;
