/* Automatically generated by './build/bin/build-el.js' */
import Button from 'element-ui/packages/button/index.js';
// Button.name = "FButton"
/* istanbul ignore next */
Button.install = function(Vue) {
    Vue.component("FButton", Button);
};
export default Button;
