/* Automatically generated by './build/bin/build-el.js' */
import Tag from 'element-ui/packages/tag/index.js';
// Tag.name = "FTag"
/* istanbul ignore next */
Tag.install = function(Vue) {
    Vue.component("FTag", Tag);
};
export default Tag;
