/* Automatically generated by './build/bin/build-el.js' */
import Calendar from 'element-ui/packages/calendar/index.js';
// Calendar.name = "CCalendar"
/* istanbul ignore next */
Calendar.install = function(Vue) {
    Vue.component("FCalendar", Calendar);
};
export default Calendar;
