/* Automatically generated by './build/bin/build-el.js' */
import MenuItemGroup from 'element-ui/packages/menu-item-group/index.js';
// MenuItemGroup.name = "FMenuItemGroup"
/* istanbul ignore next */
MenuItemGroup.install = function(Vue) {
    Vue.component("FMenuItemGroup", MenuItemGroup);
};
export default MenuItemGroup;
